name: bg_download
author: synw <ansterj@gmail.com>
description: Download a file in the background in an isolate
homepage: https://github.com/synw/bg_download
version: 0.1.0

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  dio: ^3.0.8
  meta: ^1.1.7
  iso: ^0.3.0
  filesize: ^1.0.4
